import { PGlite } from '@electric-sql/pglite';
import { readFile, readdir } from 'node:fs/promises';
import assert from 'node:assert/strict';
const db = new PGlite();
await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE SCHEMA auth;
CREATE TABLE auth.users(id uuid PRIMARY KEY, raw_user_meta_data jsonb DEFAULT '{}');
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
GRANT USAGE ON SCHEMA public,auth TO authenticated,anon;
GRANT EXECUTE ON FUNCTION auth.uid() TO authenticated,anon;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO authenticated,anon;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE ON SEQUENCES TO authenticated,anon;`);
let legacyProductFixtures=[];
for(const f of (await readdir('supabase/migrations')).sort()) {
  if(f==='20260924140000_standardize_product_codes.sql') {
    legacyProductFixtures=(await db.query(`INSERT INTO products(code,name,unit_cost,unit_price,created_at)
      VALUES('OUT-001','Abraçadeira de nylon',0.25,1,'2020-01-01'),
            ('FERR-001','Chave de teste',5,15,'2020-01-02'),
            ('FERR-007','Alicate',8,24,'2020-01-03') RETURNING id,code,name,unit_price`)).rows;
  }
  await db.exec(await readFile('supabase/migrations/'+f,'utf8'));
}
await db.exec('CREATE TABLE public.test_client_delete_guard(client_id uuid REFERENCES public.clients(id) ON DELETE RESTRICT); GRANT SELECT,INSERT,DELETE ON public.test_client_delete_guard TO authenticated;');
let checks=0;
async function sql(q,p=[]){return (await db.query(q,p)).rows;}
async function rpc(name,args){if(name==='register_payment' && args.length===3) args=[...args,(await sql('SELECT version FROM services WHERE id=$1',[args[0]]))[0]?.version??0];const ps=args.map((_,i)=>'$'+(i+1)).join(',');return (await sql(`SELECT public.${name}(${ps}) AS value`,args))[0].value;}
async function createProduct(data){const code=await rpc('reserve_product_code',[]);return rpc('create_product',[data,code]);}
async function fails(fn, pattern){await assert.rejects(fn,pattern);checks++;}
function equal(a,b){assert.deepEqual(typeof b === "number" ? Number(a) : a,b);checks++;}
const admin='11111111-1111-4111-8111-111111111111',op='22222222-2222-4222-8222-222222222222',pending='33333333-3333-4333-8333-333333333333';
await sql(`INSERT INTO auth.users(id,raw_user_meta_data) VALUES($1,'{"name":"Cj"}'),($2,'{"name":"Operador","role":"admin"}'),($3,'{}')`,[admin,op,pending]);
equal((await sql('SELECT role,is_active FROM profiles WHERE id=$1',[op]))[0],{role:'operador',is_active:false});
await sql("UPDATE profiles SET role='admin',is_active=true WHERE id=$1",[admin]);
equal(await sql('SELECT id,code,name,unit_price::float8 FROM products ORDER BY code'),legacyProductFixtures.map((p,index)=>({id:p.id,code:`PROD-${String(index+1).padStart(4,'0')}`,name:p.name,unit_price:Number(p.unit_price)})));
equal(await sql('SELECT legacy_code,product_id FROM product_code_aliases ORDER BY legacy_code'),legacyProductFixtures.map(p=>({legacy_code:p.code,product_id:p.id})).sort((a,b)=>a.legacy_code.localeCompare(b.legacy_code)));
async function as(id){await db.exec('RESET ROLE');await sql("SELECT set_config('request.jwt.claim.sub',$1,false)",[id??'']);await db.exec('SET ROLE '+(id?'authenticated':'anon'));}
await as(admin);
await rpc('set_user_access',[op,'operador',true]);
const product=await createProduct({name:'Tubo',unit_cost:10,unit_price:20});
equal((await sql('SELECT code FROM products WHERE id=$1',[product]))[0].code,'PROD-0004');
await fails(()=>sql("INSERT INTO products(code,name) VALUES('PROD-9999','Inserção direta')"),/permission denied/);
await fails(()=>sql("UPDATE products SET code='PROD-9998' WHERE id=$1",[product]),/código do produto não pode ser alterado/i);
const concurrentReservations=await Promise.all([rpc('reserve_product_code',[]),rpc('reserve_product_code',[])]);
equal(new Set(concurrentReservations).size,2);
equal(concurrentReservations.every(code=>/^PROD-\d{4,}$/.test(code)),true);
const concurrentProducts=await Promise.all(concurrentReservations.map((code,index)=>rpc('create_product',[{name:`Produto simultâneo ${index+1}`},code])));
equal(new Set(concurrentProducts).size,2);
equal((await sql('SELECT count(*)::integer n FROM products WHERE id=ANY($1::uuid[]) AND code LIKE \'PROD-%\'',[concurrentProducts]))[0].n,2);
const unusedCode=await rpc('reserve_product_code',[]);
await rpc('release_product_code_reservation',[unusedCode]);
const codeAfterCancel=await rpc('reserve_product_code',[]);
equal(Number(codeAfterCancel.slice(5))>Number(unusedCode.slice(5)),true);
await rpc('release_product_code_reservation',[codeAfterCancel]);
const client=(await sql("INSERT INTO clients(name) VALUES('Cliente') RETURNING id"))[0].id;
const movement=async(q,type='entrada',id=crypto.randomUUID())=>rpc('register_movement',[product,type,q,10,'Técnico','Teste',id]);
const balance=()=>rpc('get_product_balance',[product]);
const request=crypto.randomUUID(); const entry=await movement(10,'entrada',request);await movement(10,'entrada',request);equal(await balance(),10);
equal((await sql('SELECT responsible,created_by FROM movements WHERE id=$1',[entry]))[0],{responsible:'Cj',created_by:admin});
await fails(()=>movement(11,'entrada',request),/reutilizado/);
await as(op);
const operatorEntry=await movement(1,'entrada');
equal((await sql('SELECT responsible,created_by FROM movements WHERE id=$1',[operatorEntry]))[0],{responsible:'Operador',created_by:op});
await movement(1,'saida');
await fails(()=>sql("UPDATE profiles SET role='admin' WHERE id=$1",[op]),/permission denied/);
await fails(()=>sql("INSERT INTO products(code,name) VALUES('X','X')"),/permission denied/);
await fails(()=>rpc('reserve_product_code',[]),/administradores/);
await fails(()=>rpc('create_product',[{name:'Sem permissão'},'PROD-9999']),/administradores/);
await fails(()=>rpc('import_products',[[{code:'SEM-PERMISSAO',name:'Não importar',stock:0,min_stock:0,unit_cost:0,unit_price:0}]]),/administradores/);
await fails(()=>rpc('stock_delta',[product,99,0,'entrada','','',null,null,null]),/permission denied/);
await fails(()=>movement(-1,'saida'),/Quantidade inválida/);
await fails(()=>movement(11,'saida'),/Saldo insuficiente/);
await fails(()=>movement(-1,'ajuste'),/administradores/);
await fails(()=>sql("INSERT INTO movements(product_id,type,quantity) VALUES($1,'entrada',100)",[product]),/permission denied/);
await fails(()=>sql("UPDATE services SET total_value=0"),/permission denied/);
const input={client_id:client,service_date:'2026-09-22',description:'Instalação',technician:'Operador',labor_value:100,discount:10,notes:''};
const mats=[{product_id:product,quantity:3,unit_price:20}];
const key=crypto.randomUUID();
const service=await rpc('save_service',[null,input,mats,true,key,null]);
equal((await sql('SELECT technician,created_by FROM services WHERE id=$1',[service]))[0],{technician:'Operador',created_by:op});
equal(await balance(),7);
equal(await rpc('save_service',[null,input,mats,true,key,null]),service);equal(await balance(),7);
equal((await sql('SELECT total_value FROM services WHERE id=$1',[service]))[0].total_value,150);
await rpc('confirm_service',[service]);equal(await balance(),7);
await fails(()=>rpc('save_service',[null,input,[...mats,...mats],true,crypto.randomUUID(),null]),/Não repita/);
let ver=(await sql('SELECT version FROM services WHERE id=$1',[service]))[0].version;
await rpc('save_service',[service,input,[{...mats[0],quantity:5}],false,crypto.randomUUID(),ver]);equal(await balance(),5);
await fails(()=>rpc('save_service',[service,input,mats,true,crypto.randomUUID(),ver]),/outro usuário/);
ver=(await sql('SELECT version FROM services WHERE id=$1',[service]))[0].version;
await fails(()=>rpc('save_service',[service,input,[{...mats[0],quantity:20}],true,crypto.randomUUID(),ver]),/Saldo insuficiente/);
equal(await balance(),5);equal((await sql('SELECT quantity FROM service_materials WHERE service_id=$1',[service]))[0].quantity,5);
const count=(await sql('SELECT count(*)::integer n FROM services'))[0].n;
await fails(()=>rpc('save_service',[null,input,[{...mats[0],quantity:100}],true,crypto.randomUUID(),null]),/Saldo insuficiente/);
equal((await sql('SELECT count(*)::integer n FROM services'))[0].n,count);
await fails(()=>rpc('register_payment',[service,'2026-09-22','pix',0]),/serviço mudou/);
await rpc('register_payment',[service,'2026-09-22','pix']);await rpc('register_payment',[service,'2026-09-22','pix']);
equal((await sql("SELECT count(*)::integer n FROM service_history WHERE service_id=$1 AND action='pagamento'",[service]))[0].n,1);
await fails(()=>rpc('cancel_service',[service,[]]),/Regularize/);
await fails(()=>rpc('reverse_payment',[service,'erro']),/administradores/);
await as(admin);await rpc('reverse_payment',[service,'Data incorreta']);await rpc('register_payment',[service,'2026-09-21','dinheiro']);
await rpc('reverse_payment',[service,'Devolução efetuada manualmente']);
const material=(await sql('SELECT id FROM service_materials WHERE service_id=$1',[service]))[0].id;
await rpc('cancel_service',[service,[material]]);await rpc('cancel_service',[service,[material]]);equal(await balance(),10);
await fails(()=>rpc('confirm_service',[service]),/cancelado/);
const service2=await rpc('save_service',[null,input,mats,true,crypto.randomUUID(),null]);
const legacyMaterial=(await sql('SELECT id FROM service_materials WHERE service_id=$1',[service2]))[0].id;
const legacyVersion=(await sql('SELECT version FROM services WHERE id=$1',[service2]))[0].version;
await rpc('save_service_visit',[service2,{...input,technician:'João Silva'},[{notes:'',services:[{id:null,service_type_id:null,is_legacy:true,unit_price:100}],materials:[{id:legacyMaterial,product_id:product,quantity:3,unit_price:20}]}],false,crypto.randomUUID(),legacyVersion]);
equal((await sql('SELECT count(*)::integer n FROM service_appliances WHERE service_id=$1',[service2]))[0].n,1);
equal(await balance(),7);
await rpc('cancel_service',[service2,[]]);equal(await balance(),7);
await fails(()=>rpc('reverse_movement',[entry,'Entrada incorreta']),/Saldo insuficiente/);
const e2=await movement(2);await rpc('reverse_movement',[e2,'Erro']);await rpc('reverse_movement',[e2,'Erro']);equal(await balance(),7);
await movement(-2,'ajuste');equal(await balance(),5);
await fails(()=>movement(-6,'ajuste'),/Saldo insuficiente/);
const imp=[{code:'GAS',name:'Gás',unit:'kg',category:'Refrigeração',supplier:'',stock:2.5,min_stock:1,unit_cost:10,unit_price:20}];
equal((await rpc('import_products',[imp])).imported,1);equal((await rpc('import_products',[imp])).skipped,1);
await db.exec('RESET ROLE');
const importedGas=(await sql("SELECT p.id,p.code FROM products p JOIN product_code_aliases a ON a.product_id=p.id WHERE a.legacy_code='GAS'"))[0];
equal(/^PROD-\d{4,}$/.test(importedGas.code),true);
equal((await sql("SELECT legacy_code FROM product_code_aliases WHERE product_id=$1",[importedGas.id]))[0].legacy_code,'GAS');
await as(admin);
await fails(()=>rpc('import_products',[[{...imp[0],code:'INVALID',stock:-2}]]),/inválido/);
await as(admin);
const cleanType=(await sql("INSERT INTO service_types(name,default_price) VALUES('Limpeza',100) RETURNING id"))[0].id;
const gasType=(await sql("INSERT INTO service_types(name,default_price) VALUES('Troca de gás',50) RETURNING id"))[0].id;
const installType=(await sql("INSERT INTO service_types(name,default_price) VALUES('Instalação',300) RETURNING id"))[0].id;
const productY=await createProduct({name:'Capacitor',unit_cost:5,unit_price:25});
await rpc('register_movement',[productY,'entrada',3,5,'Nome adulterado','Estoque inicial',crypto.randomUUID()]);
const visit={client_id:client,service_date:'2026-09-22',description:'Atendimento de dois aparelhos',technician:'João Silva',discount:0,notes:'Observação geral'};
const devices=[
 {notes:'Sala',services:[{id:null,service_type_id:cleanType,unit_price:100},{id:null,service_type_id:gasType,unit_price:50}],materials:[{product_id:product,quantity:2,unit_price:12}]},
 {notes:'Quarto',services:[{id:null,service_type_id:installType,unit_price:300}],materials:[{product_id:productY,quantity:1,unit_price:25}]},
];
const visitKey=crypto.randomUUID();
await fails(()=>rpc('save_service_visit',[null,{...visit,technician:'   '},devices,false,crypto.randomUUID(),null]),/técnico responsável/);
const visitId=await rpc('save_service_visit',[null,visit,devices,true,visitKey,null]);
equal((await sql('SELECT technician,created_by,labor_value::float8,total_value::float8 FROM services WHERE id=$1',[visitId]))[0],{technician:'João Silva',created_by:admin,labor_value:450,total_value:499});
const devicesDb=await sql('SELECT id,appliance_number,notes FROM service_appliances WHERE service_id=$1 ORDER BY appliance_number',[visitId]);
equal(devicesDb.map(d=>[d.appliance_number,d.notes]),[[1,'Sala'],[2,'Quarto']]);
equal((await sql('SELECT sum(unit_price)::numeric total FROM performed_services WHERE appliance_id=$1',[devicesDb[0].id]))[0].total,150);
equal((await sql('SELECT sum(subtotal)::numeric total FROM service_materials WHERE appliance_id=$1',[devicesDb[0].id]))[0].total,24);
equal((await sql('SELECT sum(unit_price)::numeric total FROM performed_services WHERE appliance_id=$1',[devicesDb[1].id]))[0].total,300);
equal((await sql('SELECT sum(subtotal)::numeric total FROM service_materials WHERE appliance_id=$1',[devicesDb[1].id]))[0].total,25);
equal((await sql('SELECT created_by FROM movements WHERE service_id=$1 AND type=\'saida\' ORDER BY id LIMIT 1',[visitId]))[0].created_by,admin);
equal(await balance(),3);
equal((await sql('SELECT count(*)::integer n FROM performed_services WHERE appliance_id IN (SELECT id FROM service_appliances WHERE service_id=$1)',[visitId]))[0].n,3);
equal((await sql('SELECT unit_price FROM products WHERE id=$1',[product]))[0].unit_price,20);
equal((await sql('SELECT unit_price FROM service_materials WHERE service_id=$1 AND product_id=$2',[visitId,product]))[0].unit_price,12);
equal(await rpc('save_service_visit',[null,visit,devices,true,visitKey,null]),visitId);
equal((await sql('SELECT count(*)::integer n FROM service_appliances WHERE service_id=$1',[visitId]))[0].n,2);
const currentTasks=await sql('SELECT id,appliance_id,service_type_id,unit_price FROM performed_services WHERE appliance_id IN (SELECT id FROM service_appliances WHERE service_id=$1) ORDER BY id',[visitId]);
const currentMaterials=await sql('SELECT id,appliance_id,product_id,quantity,unit_price FROM service_materials WHERE service_id=$1 ORDER BY appliance_id',[visitId]);
const editedDevices=devicesDb.map((device,index)=>({notes:index===0?'Sala atualizada':'Quarto',services:currentTasks.filter(t=>t.appliance_id===device.id).map(t=>({id:t.id,service_type_id:t.service_type_id,unit_price:Number(t.unit_price)+(t.service_type_id===installType?50:0)})),materials:currentMaterials.filter(m=>m.appliance_id===device.id).map(m=>({id:m.id,product_id:m.product_id,quantity:Number(m.quantity),unit_price:Number(m.unit_price)+(m.product_id===product?0.5:0)}))}));
const editedVisit={...visit};
const currentVersion=(await sql('SELECT version FROM services WHERE id=$1',[visitId]))[0].version;
await rpc('save_service_visit',[visitId,editedVisit,editedDevices,false,crypto.randomUUID(),currentVersion]);
equal((await sql('SELECT total_value::float8 FROM services WHERE id=$1',[visitId]))[0].total_value,550);
equal((await sql('SELECT technician FROM services WHERE id=$1',[visitId]))[0].technician,'João Silva');
equal(await balance(),3);
equal((await sql("SELECT count(*)::integer n FROM service_history WHERE service_id=$1 AND action='edicao'",[visitId]))[0].n,1);
const unusedServiceType=(await sql("INSERT INTO service_types(name,default_price) VALUES('Serviço de teste sem histórico',10) RETURNING id"))[0].id;
await fails(()=>sql('DELETE FROM service_types WHERE id=$1',[unusedServiceType]),/permission denied/);
await rpc('delete_service_type',[unusedServiceType]);
equal((await sql('SELECT count(*)::integer n FROM service_types WHERE id=$1',[unusedServiceType]))[0].n,0);
await fails(()=>rpc('delete_service_type',[cleanType]),/já foi utilizado/);
equal((await sql('SELECT count(*)::integer n FROM performed_services WHERE service_type_id=$1',[cleanType]))[0].n,1);
const protectedServiceType=(await sql("INSERT INTO service_types(name,default_price) VALUES('Tipo protegido',10) RETURNING id"))[0].id;
await as(op);
await fails(()=>rpc('delete_service_type',[protectedServiceType]),/administradores/);
equal((await sql('SELECT count(*)::integer n FROM service_types WHERE id=$1',[protectedServiceType]))[0].n,1);
await as(admin);
await sql("UPDATE service_types SET is_active=false WHERE id=$1",[cleanType]);
equal((await sql('SELECT is_active FROM service_types WHERE id=$1',[cleanType]))[0].is_active,false);
equal((await sql('SELECT name_snapshot,unit_price::float8 FROM performed_services WHERE service_type_id=$1 ORDER BY created_at LIMIT 1',[cleanType]))[0],{name_snapshot:'Limpeza',unit_price:100});
await sql("UPDATE service_types SET is_active=true WHERE id=$1",[cleanType]);
equal((await sql('SELECT is_active FROM service_types WHERE id=$1',[cleanType]))[0].is_active,true);
await fails(()=>rpc('delete_product',[productY]),/histórico/);
equal((await sql('SELECT count(*)::integer n FROM products WHERE id=$1',[productY]))[0].n,1);
const emptyProduct=await createProduct({name:'Sem histórico'});
const removedCode=(await sql('SELECT code FROM products WHERE id=$1',[emptyProduct]))[0].code;
await rpc('delete_product',[emptyProduct]);
equal((await sql('SELECT count(*)::integer n FROM products WHERE id=$1',[emptyProduct]))[0].n,0);
const afterDeleteProduct=await createProduct({name:'Criado após exclusão'});
const afterDeleteCode=(await sql('SELECT code FROM products WHERE id=$1',[afterDeleteProduct]))[0].code;
equal(afterDeleteCode===removedCode,false);
equal(Number(afterDeleteCode.slice(5))>Number(removedCode.slice(5)),true);
const archivedClient=(await sql("INSERT INTO clients(name) VALUES('Cliente Arquivado') RETURNING id"))[0].id;
const archivedVisit=await rpc('save_service_visit',[null,{...visit,client_id:archivedClient},[{notes:'Unidade de teste',services:[{id:null,service_type_id:cleanType,unit_price:100}],materials:[]}],false,crypto.randomUUID(),null]);
const archivedAppliance=(await sql('SELECT id FROM service_appliances WHERE service_id=$1',[archivedVisit]))[0].id;
equal((await sql('SELECT count(*)::integer n FROM performed_services WHERE appliance_id=$1',[archivedAppliance]))[0].n,1);
await fails(()=>rpc('permanently_delete_archived_client',[archivedClient,'Cliente Arquivado']),/precisa ser arquivado/);
await db.exec('RESET ROLE');
await sql("INSERT INTO movements(product_id,type,quantity,unit_cost,responsible,notes,client_id,service_id,created_by) VALUES($1,'saida',-0.25,5,'Teste','Lançamento preservado',$2,$3,$4)",[product,archivedClient,archivedVisit,admin]);
await db.exec('SET ROLE authenticated');
const preservedMovement=(await sql('SELECT id FROM movements WHERE client_id=$1 AND service_id=$2',[archivedClient,archivedVisit]))[0].id;
await rpc('set_client_archived',[archivedClient,true]);
equal(Boolean((await sql('SELECT archived_at FROM clients WHERE id=$1',[archivedClient]))[0].archived_at),true);
await fails(()=>rpc('save_service_visit',[null,{...visit,client_id:archivedClient},[{notes:'Novo',services:[],materials:[]}],false,crypto.randomUUID(),null]),/Cliente arquivado/);
await as(op);
await fails(()=>rpc('permanently_delete_archived_client',[archivedClient,'Cliente Arquivado']),/administradores/);
await fails(()=>rpc('set_client_archived',[archivedClient,false]),/administradores/);
await as(admin);
await fails(()=>rpc('permanently_delete_archived_client',[archivedClient,'Cliente arquivado']),/não corresponde exatamente/);
await fails(()=>sql('DELETE FROM clients WHERE id=$1',[archivedClient]),/permission denied/);
await rpc('set_client_archived',[archivedClient,false]);
equal((await sql('SELECT archived_at FROM clients WHERE id=$1',[archivedClient]))[0].archived_at,null);
await fails(()=>rpc('permanently_delete_archived_client',[archivedClient,'Cliente Arquivado']),/precisa ser arquivado/);
await rpc('set_client_archived',[archivedClient,true]);
await sql('INSERT INTO test_client_delete_guard(client_id) VALUES($1)',[archivedClient]);
await fails(()=>rpc('permanently_delete_archived_client',[archivedClient,'Cliente Arquivado']),/test_client_delete_guard/);
equal((await sql('SELECT count(*)::integer n FROM services WHERE id=$1',[archivedVisit]))[0].n,1);
equal((await sql('SELECT count(*)::integer n FROM service_appliances WHERE service_id=$1',[archivedVisit]))[0].n,1);
equal((await sql('SELECT count(*)::integer n FROM performed_services WHERE appliance_id=$1',[archivedAppliance]))[0].n,1);
equal((await sql('SELECT count(*)::integer n FROM movements WHERE id=$1 AND client_id=$2 AND service_id=$3',[preservedMovement,archivedClient,archivedVisit]))[0].n,1);
await sql('DELETE FROM test_client_delete_guard WHERE client_id=$1',[archivedClient]);
equal((await sql('SELECT count(*)::integer n FROM services WHERE id=$1',[archivedVisit]))[0].n,1);
await rpc('permanently_delete_archived_client',[archivedClient,'Cliente Arquivado']);
equal((await sql('SELECT count(*)::integer n FROM clients WHERE id=$1',[archivedClient]))[0].n,0);
equal((await sql('SELECT count(*)::integer n FROM services WHERE id=$1',[archivedVisit]))[0].n,0);
equal((await sql('SELECT count(*)::integer n FROM service_appliances WHERE service_id=$1',[archivedVisit]))[0].n,0);
equal((await sql('SELECT count(*)::integer n FROM performed_services WHERE appliance_id=$1',[archivedAppliance]))[0].n,0);
equal((await sql('SELECT client_id,service_id,quantity::float8 FROM movements WHERE id=$1',[preservedMovement]))[0],{client_id:null,service_id:null,quantity:-0.25});
await db.exec('RESET ROLE');
equal((await sql('SELECT count(*)::integer n FROM operation_requests WHERE actor=$1',[op]))[0].n>0,true);
equal((await sql("SELECT count(*)::integer n FROM service_history WHERE service_id=$1 AND user_name='Operador'",[service]))[0].n>0,true);
await fails(()=>sql('DELETE FROM auth.users WHERE id=$1',[admin]),/último administrador/);
equal((await sql('SELECT count(*)::integer n FROM auth.users WHERE id=$1',[admin]))[0].n,1);
await sql('DELETE FROM auth.users WHERE id=$1',[op]);
equal((await sql('SELECT count(*)::integer n FROM profiles WHERE id=$1',[op]))[0].n,0);
equal((await sql('SELECT created_by FROM services WHERE id=$1',[service]))[0].created_by,null);
equal((await sql('SELECT count(*)::integer n FROM movements WHERE created_by=$1',[op]))[0].n,0);
equal((await sql("SELECT count(*)::integer n FROM service_history WHERE service_id=$1 AND user_name='Operador'",[service]))[0].n>0,true);
equal((await sql('SELECT count(*)::integer n FROM operation_requests WHERE actor=$1',[op]))[0].n,0);
await as(admin);
await as(pending);equal(await sql('SELECT id FROM products'),[]);await fails(()=>balance(),/não autorizado/);
await as(null);await fails(()=>balance(),/permission denied/);
await db.close();console.log(`PASS: migrations and ${checks} database assertions (roles, atomic rollback, idempotency, corrections, payments, returns, import).`);
