import { PGlite } from '@electric-sql/pglite';
import { readFile, readdir } from 'node:fs/promises';
import assert from 'node:assert/strict';
const db = new PGlite();
await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE SCHEMA auth;
CREATE TABLE auth.users(id uuid PRIMARY KEY, raw_user_meta_data jsonb DEFAULT '{}');
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
GRANT USAGE ON SCHEMA public,auth TO authenticated,anon;
GRANT EXECUTE ON FUNCTION auth.uid() TO authenticated,anon;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO authenticated,anon;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE ON SEQUENCES TO authenticated,anon;`);
let legacyProductFixtures=[];
for(const f of (await readdir('supabase/migrations')).sort()) {
  if(f==='20260924140000_standardize_product_codes.sql') {
    legacyProductFixtures=(await db.query(`INSERT INTO products(code,name,unit_cost,unit_price,created_at)
      VALUES('OUT-001','Abraçadeira de nylon',0.25,1,'2020-01-01'),
            ('FERR-001','Chave de teste',5,15,'2020-01-02'),
            ('FERR-007','Alicate',8,24,'2020-01-03') RETURNING id,code,name,unit_price`)).rows;
  }
  if (f === '20261001190000_service_actor_and_appointment_hours.sql') {
    // Simulate a remote database whose older trigger still overwrites the technician.
    await db.exec(`CREATE OR REPLACE FUNCTION public.set_service_actor() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$ BEGIN NEW.technician := (SELECT name FROM profiles WHERE id=auth.uid()); IF TG_OP='INSERT' THEN NEW.created_by := auth.uid(); END IF; RETURN NEW; END; $$;`);
  }
  await db.exec(await readFile('supabase/migrations/'+f,'utf8'));
}
await db.exec('CREATE TABLE public.test_client_delete_guard(client_id uuid REFERENCES public.clients(id) ON DELETE RESTRICT); GRANT SELECT,INSERT,DELETE ON public.test_client_delete_guard TO authenticated;');
let checks=0;
async function sql(q,p=[]){return (await db.query(q,p)).rows;}
async function rpc(name,args){if(name==='register_payment' && args.length===3) args=[...args,(await sql('SELECT version FROM services WHERE id=$1',[args[0]]))[0]?.version??0];const ps=args.map((_,i)=>'$'+(i+1)).join(',');return (await sql(`SELECT public.${name}(${ps}) AS value`,args))[0].value;}
async function createProduct(data){const code=await rpc('reserve_product_code',[]);return rpc('create_product',[data,code]);}
async function fails(fn, pattern){await assert.rejects(fn,pattern);checks++;}
function equal(a,b){assert.deepEqual(typeof b === "number" ? Number(a) : a,b);checks++;}
const admin='11111111-1111-4111-8111-111111111111',op='22222222-2222-4222-8222-222222222222',pending='33333333-3333-4333-8333-333333333333';
await sql(`INSERT INTO auth.users(id,raw_user_meta_data) VALUES($1,'{"name":"Cj"}'),($2,'{"name":"Operador","role":"admin"}'),($3,'{}')`,[admin,op,pending]);
equal((await sql('SELECT role,is_active FROM profiles WHERE id=$1',[op]))[0],{role:'operador',is_active:false});
await sql("UPDATE profiles SET role='admin',is_active=true WHERE id=$1",[admin]);
equal(await sql('SELECT id,code,name,unit_price::float8 FROM products ORDER BY code'),legacyProductFixtures.map((p,index)=>({id:p.id,code:`PROD-${String(index+1).padStart(4,'0')}`,name:p.name,unit_price:Number(p.unit_price)})));
equal(await sql('SELECT legacy_code,product_id FROM product_code_aliases ORDER BY legacy_code'),legacyProductFixtures.map(p=>({legacy_code:p.code,product_id:p.id})).sort((a,b)=>a.legacy_code.localeCompare(b.legacy_code)));
async function as(id){await db.exec('RESET ROLE');await sql("SELECT set_config('request.jwt.claim.sub',$1,false)",[id??'']);await db.exec('SET ROLE '+(id?'authenticated':'anon'));}
await as(admin);
await rpc('set_user_access',[op,'operador',true]);
const product=await createProduct({name:'Tubo',unit_cost:10,unit_price:20});
equal((await sql('SELECT code FROM products WHERE id=$1',[product]))[0].code,'PROD-0004');
await fails(()=>sql("INSERT INTO products(code,name) VALUES('PROD-9999','Inserção direta')"),/permission denied/);
await fails(()=>sql("UPDATE products SET code='PROD-9998' WHERE id=$1",[product]),/código do produto não pode ser alterado/i);
const concurrentReservations=await Promise.all([rpc('reserve_product_code',[]),rpc('reserve_product_code',[])]);
equal(new Set(concurrentReservations).size,2);
equal(concurrentReservations.every(code=>/^PROD-\d{4,}$/.test(code)),true);
const concurrentProducts=await Promise.all(concurrentReservations.map((code,index)=>rpc('create_product',[{name:`Produto simultâneo ${index+1}`},code])));
equal(new Set(concurrentProducts).size,2);
equal((await sql('SELECT count(*)::integer n FROM products WHERE id=ANY($1::uuid[]) AND code LIKE \'PROD-%\'',[concurrentProducts]))[0].n,2);
const unusedCode=await rpc('reserve_product_code',[]);
await rpc('release_product_code_reservation',[unusedCode]);
const codeAfterCancel=await rpc('reserve_product_code',[]);
equal(Number(codeAfterCancel.slice(5))>Number(unusedCode.slice(5)),true);
await rpc('release_product_code_reservation',[codeAfterCancel]);
const client=(await sql("INSERT INTO clients(name) VALUES('Cliente') RETURNING id"))[0].id;
const movement=async(q,type='entrada',id=crypto.randomUUID())=>rpc('register_movement',[product,type,q,10,'Técnico','Teste',id]);
const balance=()=>rpc('get_product_balance',[product]);
const request=crypto.randomUUID(); const entry=await movement(10,'entrada',request);await movement(10,'entrada',request);equal(await balance(),10);
equal((await sql('SELECT responsible,created_by FROM movements WHERE id=$1',[entry]))[0],{responsible:'Cj',created_by:admin});
await fails(()=>movement(11,'entrada',request),/reutilizado/);
await as(op);
const operatorEntry=await movement(1,'entrada');
equal((await sql('SELECT responsible,created_by FROM movements WHERE id=$1',[operatorEntry]))[0],{responsible:'Operador',created_by:op});
await movement(1,'saida');
await fails(()=>sql("UPDATE profiles SET role='admin' WHERE id=$1",[op]),/permission denied/);
await fails(()=>sql("INSERT INTO products(code,name) VALUES('X','X')"),/permission denied/);
await fails(()=>rpc('reserve_product_code',[]),/administradores/);
await fails(()=>rpc('create_product',[{name:'Sem permissão'},'PROD-9999']),/administradores/);
await fails(()=>rpc('import_products',[[{code:'SEM-PERMISSAO',name:'Não importar',stock:0,min_stock:0,unit_cost:0,unit_price:0}]]),/administradores/);
await fails(()=>rpc('stock_delta',[product,99,0,'entrada','','',null,null,null]),/permission denied/);
await fails(()=>movement(-1,'saida'),/Quantidade inválida/);
await fails(()=>movement(11,'saida'),/Saldo insuficiente/);
await fails(()=>movement(-1,'ajuste'),/administradores/);
await fails(()=>sql("INSERT INTO movements(product_id,type,quantity) VALUES($1,'entrada',100)",[product]),/permission denied/);
await fails(()=>sql("UPDATE services SET total_value=0"),/permission denied/);
const input={client_id:client,service_date:'2026-09-22',description:'Instalação',technician:'Operador',labor_value:100,discount:10,notes:''};
const mats=[{product_id:product,quantity:3,unit_price:20}];
const key=crypto.randomUUID();
const service=await rpc('save_service',[null,input,mats,true,key,null]);
equal((await sql('SELECT technician,created_by FROM services WHERE id=$1',[service]))[0],{technician:'Operador',created_by:op});
equal(await balance(),7);
equal(await rpc('save_service',[null,input,mats,true,key,null]),service);equal(await balance(),7);
equal((await sql('SELECT total_value FROM services WHERE id=$1',[service]))[0].total_value,150);
await rpc('confirm_service',[service]);equal(await balance(),7);
await fails(()=>rpc('save_service',[null,input,[...mats,...mats],true,crypto.randomUUID(),null]),/Não repita/);
let ver=(await sql('SELECT version FROM services WHERE id=$1',[service]))[0].version;
await rpc('save_service',[service,input,[{...mats[0],quantity:5}],false,crypto.randomUUID(),ver]);equal(await balance(),5);
await fails(()=>rpc('save_service',[service,input,mats,true,crypto.randomUUID(),ver]),/outro usuário/);
ver=(await sql('SELECT version FROM services WHERE id=$1',[service]))[0].version;
await fails(()=>rpc('save_service',[service,input,[{...mats[0],quantity:20}],true,crypto.randomUUID(),ver]),/Saldo insuficiente/);
equal(await balance(),5);equal((await sql('SELECT quantity FROM service_materials WHERE service_id=$1',[service]))[0].quantity,5);
const count=(await sql('SELECT count(*)::integer n FROM services'))[0].n;
await fails(()=>rpc('save_service',[null,input,[{...mats[0],quantity:100}],true,crypto.randomUUID(),null]),/Saldo insuficiente/);
equal((await sql('SELECT count(*)::integer n FROM services'))[0].n,count);
const registerDate=(await sql("SELECT (now() AT TIME ZONE 'America/Sao_Paulo')::date::text AS date"))[0].date;
ver=(await sql('SELECT version FROM services WHERE id=$1',[service]))[0].version;
await fails(()=>rpc('register_payment',[service,registerDate,'pix',ver]),/Abra o caixa/);
equal((await sql('SELECT payment_status FROM services WHERE id=$1',[service]))[0].payment_status,'pendente');
const cashRegister=await rpc('open_cash_register',[registerDate,100]);
await fails(()=>rpc('open_cash_register',[registerDate,0]),/caixa/);
await fails(()=>rpc('register_payment',[service,'2026-09-22','pix',0]),/serviço mudou/);
await rpc('register_payment',[service,'2026-09-22','pix']);await rpc('register_payment',[service,'2026-09-22','pix']);
equal((await sql("SELECT count(*)::integer n FROM service_history WHERE service_id=$1 AND action='pagamento'",[service]))[0].n,1);
let registerSnapshot=await rpc('cash_register_snapshot',[cashRegister]);
equal(registerSnapshot.movements.filter(m=>m.source==='service_payment').length,1);
await fails(()=>rpc('cancel_service',[service,[]]),/Regularize/);
await fails(()=>rpc('reverse_payment',[service,'erro']),/administradores/);
await as(admin);await rpc('reverse_payment',[service,'Data incorreta']);await rpc('register_payment',[service,'2026-09-21','dinheiro']);
await rpc('reverse_payment',[service,'Devolução efetuada manualmente']);
registerSnapshot=await rpc('cash_register_snapshot',[cashRegister]);
equal(registerSnapshot.movements.filter(m=>m.source==='payment_reversal').length,2);
const material=(await sql('SELECT id FROM service_materials WHERE service_id=$1',[service]))[0].id;
await rpc('cancel_service',[service,[material]]);await rpc('cancel_service',[service,[material]]);equal(await balance(),10);
await fails(()=>rpc('confirm_service',[service]),/cancelado/);
const cashService=(description,amount)=>rpc('save_service',[null,{...input,description,labor_value:amount,discount:0},[],true,crypto.randomUUID(),null]);
const cashService500=await cashService('Serviço recebido em dinheiro',500);
const cashService300=await cashService('Serviço recebido em Pix',300);
await rpc('register_payment',[cashService500,registerDate,'dinheiro']);
await rpc('register_payment',[cashService300,registerDate,'pix']);
await rpc('register_payment',[cashService500,registerDate,'dinheiro']);
await as(op);
await rpc('record_cash_movement',[cashRegister,'saida','Combustível',50,'dinheiro',null]);
await fails(()=>rpc('record_cash_movement',[cashRegister,'ajuste','Correção',10,'dinheiro','Teste']),/administradores/);
await as(admin);
await rpc('record_cash_movement',[cashRegister,'ajuste','Ajuste positivo',10,'dinheiro','Conferência']);
await rpc('record_cash_movement',[cashRegister,'ajuste','Ajuste de compensação',-10,'dinheiro','Conferência']);
registerSnapshot=await rpc('cash_register_snapshot',[cashRegister]);
equal(Number(registerSnapshot.expected_balance),850);
equal(Number(registerSnapshot.expected_cash_live),550);
equal(Number(registerSnapshot.method_totals.dinheiro),550);
equal(Number(registerSnapshot.method_totals.pix),300);
equal(Number(registerSnapshot.income),1180);
equal(Number(registerSnapshot.outgoing),430);
equal(Number(registerSnapshot.adjustment),0);
await fails(()=>rpc('close_cash_register',[cashRegister,551,null]),/motivo da diferença/);
const positiveClose=await rpc('close_cash_register',[cashRegister,560,'Sobra na conferência']);
equal(Number(positiveClose.difference),10);
await db.exec('RESET ROLE');
await sql("UPDATE cash_registers SET status='aberto',closing_balance=NULL,expected_cash=NULL,counted_cash=NULL,difference=NULL,closing_reason=NULL,closed_by=NULL,closed_by_name='',closed_at=NULL WHERE id=$1",[cashRegister]);
await as(admin);
const negativeClose=await rpc('close_cash_register',[cashRegister,540,'Falta na conferência']);
equal(Number(negativeClose.difference),-10);
await db.exec('RESET ROLE');
await sql("UPDATE cash_registers SET status='aberto',closing_balance=NULL,expected_cash=NULL,counted_cash=NULL,difference=NULL,closing_reason=NULL,closed_by=NULL,closed_by_name='',closed_at=NULL WHERE id=$1",[cashRegister]);
await as(admin);
const closeResult=await rpc('close_cash_register',[cashRegister,550,'']);
equal(Number(closeResult.difference),0);
equal(Number(closeResult.closing_balance),850);
equal(Number(closeResult.expected_cash),550);
await fails(()=>rpc('record_cash_movement',[cashRegister,'entrada','Depois do fechamento',1,'dinheiro',null]),/caixa aberto/);
await fails(()=>sql("UPDATE cash_registers SET status='aberto' WHERE id=$1",[cashRegister]),/permission denied/);
await fails(()=>rpc('reverse_payment',[cashService500,'Estorno após fechamento']),/Abra o caixa/);
equal((await sql('SELECT payment_status FROM services WHERE id=$1',[cashService500]))[0].payment_status,'pago');
const postedPaymentsBeforeRetry=registerSnapshot.movements.filter(m=>m.source==='service_payment').length;
await rpc('register_payment',[cashService500,registerDate,'dinheiro']);
registerSnapshot=await rpc('cash_register_snapshot',[cashRegister]);
equal(registerSnapshot.movements.filter(m=>m.source==='service_payment').length,postedPaymentsBeforeRetry);
const serviceWithoutCash=await cashService('Pagamento sem caixa aberto',25);
await fails(()=>rpc('register_payment',[serviceWithoutCash,registerDate,'pix']),/Abra o caixa/);
equal((await sql('SELECT payment_status FROM services WHERE id=$1',[serviceWithoutCash]))[0].payment_status,'pendente');
equal((await rpc('cash_register_history',[90])).some(r=>r.id===cashRegister),true);
const service2=await rpc('save_service',[null,input,mats,true,crypto.randomUUID(),null]);
const legacyMaterial=(await sql('SELECT id FROM service_materials WHERE service_id=$1',[service2]))[0].id;
const legacyVersion=(await sql('SELECT version FROM services WHERE id=$1',[service2]))[0].version;
await rpc('save_service_visit',[service2,{...input,technician:'João Silva'},[{notes:'',services:[{id:null,service_type_id:null,is_legacy:true,unit_price:100}],materials:[{id:legacyMaterial,product_id:product,quantity:3,unit_price:20}]}],false,crypto.randomUUID(),legacyVersion]);
equal((await sql('SELECT count(*)::integer n FROM service_appliances WHERE service_id=$1',[service2]))[0].n,1);
equal(await balance(),7);
await rpc('cancel_service',[service2,[]]);equal(await balance(),7);
await fails(()=>rpc('reverse_movement',[entry,'Entrada incorreta']),/Saldo insuficiente/);
const e2=await movement(2);await rpc('reverse_movement',[e2,'Erro']);await rpc('reverse_movement',[e2,'Erro']);equal(await balance(),7);
await movement(-2,'ajuste');equal(await balance(),5);
await fails(()=>movement(-6,'ajuste'),/Saldo insuficiente/);
const imp=[{code:'GAS',name:'Gás',unit:'kg',category:'Refrigeração',supplier:'',stock:2.5,min_stock:1,unit_cost:10,unit_price:20}];
equal((await rpc('import_products',[imp])).imported,1);equal((await rpc('import_products',[imp])).skipped,1);
await db.exec('RESET ROLE');
const importedGas=(await sql("SELECT p.id,p.code FROM products p JOIN product_code_aliases a ON a.product_id=p.id WHERE a.legacy_code='GAS'"))[0];
equal(/^PROD-\d{4,}$/.test(importedGas.code),true);
equal((await sql("SELECT legacy_code FROM product_code_aliases WHERE product_id=$1",[importedGas.id]))[0].legacy_code,'GAS');
await as(admin);
await fails(()=>rpc('import_products',[[{...imp[0],code:'INVALID',stock:-2}]]),/inválido/);
await as(admin);
const cleanType=(await sql("INSERT INTO service_types(name,default_price) VALUES('Limpeza',100) RETURNING id"))[0].id;
const gasType=(await sql("INSERT INTO service_types(name,default_price) VALUES('Troca de gás',50) RETURNING id"))[0].id;
const installType=(await sql("INSERT INTO service_types(name,default_price) VALUES('Instalação',300) RETURNING id"))[0].id;
const productY=await createProduct({name:'Capacitor',unit_cost:5,unit_price:25});
await rpc('register_movement',[productY,'entrada',3,5,'Nome adulterado','Estoque inicial',crypto.randomUUID()]);
const visit={client_id:client,service_date:'2026-09-22',description:'Atendimento de dois aparelhos',technician:'João Silva',discount:0,notes:'Observação geral'};
const devices=[
 {notes:'Sala',services:[{id:null,service_type_id:cleanType,unit_price:100},{id:null,service_type_id:gasType,unit_price:50}],materials:[{product_id:product,quantity:2,unit_price:12}]},
 {notes:'Quarto',services:[{id:null,service_type_id:installType,unit_price:300}],materials:[{product_id:productY,quantity:1,unit_price:25}]},
];
const visitKey=crypto.randomUUID();
await fails(()=>rpc('save_service_visit',[null,{...visit,technician:'   '},devices,false,crypto.randomUUID(),null]),/técnico responsável/);
const visitId=await rpc('save_service_visit',[null,visit,devices,true,visitKey,null]);
equal((await sql('SELECT technician,created_by,labor_value::float8,total_value::float8 FROM services WHERE id=$1',[visitId]))[0],{technician:'João Silva',created_by:admin,labor_value:450,total_value:499});
const devicesDb=await sql('SELECT id,appliance_number,notes FROM service_appliances WHERE service_id=$1 ORDER BY appliance_number',[visitId]);
equal(devicesDb.map(d=>[d.appliance_number,d.notes]),[[1,'Sala'],[2,'Quarto']]);
equal((await sql('SELECT sum(unit_price)::numeric total FROM performed_services WHERE appliance_id=$1',[devicesDb[0].id]))[0].total,150);
equal((await sql('SELECT sum(subtotal)::numeric total FROM service_materials WHERE appliance_id=$1',[devicesDb[0].id]))[0].total,24);
equal((await sql('SELECT sum(unit_price)::numeric total FROM performed_services WHERE appliance_id=$1',[devicesDb[1].id]))[0].total,300);
equal((await sql('SELECT sum(subtotal)::numeric total FROM service_materials WHERE appliance_id=$1',[devicesDb[1].id]))[0].total,25);
equal((await sql('SELECT created_by FROM movements WHERE service_id=$1 AND type=\'saida\' ORDER BY id LIMIT 1',[visitId]))[0].created_by,admin);
equal(await balance(),3);
equal((await sql('SELECT count(*)::integer n FROM performed_services WHERE appliance_id IN (SELECT id FROM service_appliances WHERE service_id=$1)',[visitId]))[0].n,3);
equal((await sql('SELECT unit_price FROM products WHERE id=$1',[product]))[0].unit_price,20);
equal((await sql('SELECT unit_price FROM service_materials WHERE service_id=$1 AND product_id=$2',[visitId,product]))[0].unit_price,12);
equal(await rpc('save_service_visit',[null,visit,devices,true,visitKey,null]),visitId);
equal((await sql('SELECT count(*)::integer n FROM service_appliances WHERE service_id=$1',[visitId]))[0].n,2);
const currentTasks=await sql('SELECT id,appliance_id,service_type_id,unit_price FROM performed_services WHERE appliance_id IN (SELECT id FROM service_appliances WHERE service_id=$1) ORDER BY id',[visitId]);
const currentMaterials=await sql('SELECT id,appliance_id,product_id,quantity,unit_price FROM service_materials WHERE service_id=$1 ORDER BY appliance_id',[visitId]);
const editedDevices=devicesDb.map((device,index)=>({notes:index===0?'Sala atualizada':'Quarto',services:currentTasks.filter(t=>t.appliance_id===device.id).map(t=>({id:t.id,service_type_id:t.service_type_id,unit_price:Number(t.unit_price)+(t.service_type_id===installType?50:0)})),materials:currentMaterials.filter(m=>m.appliance_id===device.id).map(m=>({id:m.id,product_id:m.product_id,quantity:Number(m.quantity),unit_price:Number(m.unit_price)+(m.product_id===product?0.5:0)}))}));
const editedVisit={...visit};
const currentVersion=(await sql('SELECT version FROM services WHERE id=$1',[visitId]))[0].version;
await rpc('save_service_visit',[visitId,editedVisit,editedDevices,false,crypto.randomUUID(),currentVersion]);
equal((await sql('SELECT total_value::float8 FROM services WHERE id=$1',[visitId]))[0].total_value,550);
equal((await sql('SELECT technician FROM services WHERE id=$1',[visitId]))[0].technician,'João Silva');
equal(await balance(),3);
equal((await sql("SELECT count(*)::integer n FROM service_history WHERE service_id=$1 AND action='edicao'",[visitId]))[0].n,1);
const unusedServiceType=(await sql("INSERT INTO service_types(name,default_price) VALUES('Serviço de teste sem histórico',10) RETURNING id"))[0].id;
await fails(()=>sql('DELETE FROM service_types WHERE id=$1',[unusedServiceType]),/permission denied/);
await rpc('delete_service_type',[unusedServiceType]);
equal((await sql('SELECT count(*)::integer n FROM service_types WHERE id=$1',[unusedServiceType]))[0].n,0);
equal((await sql('SELECT name_snapshot,description_snapshot,unit_price::float8 FROM performed_services WHERE service_type_id=$1',[cleanType]))[0],{name_snapshot:'Limpeza',description_snapshot:'',unit_price:100});
await rpc('delete_service_type',[cleanType]);
equal((await sql('SELECT count(*)::integer n FROM service_types WHERE id=$1',[cleanType]))[0].n,0);
equal((await sql('SELECT service_type_id,name_snapshot,description_snapshot,unit_price::float8 FROM performed_services WHERE name_snapshot=$1',["Limpeza"]))[0],{service_type_id:null,name_snapshot:'Limpeza',description_snapshot:'',unit_price:100});
const preservedAppliances=await sql('SELECT id,appliance_number,notes FROM service_appliances WHERE service_id=$1 ORDER BY appliance_number',[visitId]);
const deletedTypeTasks=await sql('SELECT id,appliance_id,service_type_id,unit_price::float8 unit_price FROM performed_services WHERE appliance_id IN (SELECT id FROM service_appliances WHERE service_id=$1)',[visitId]);
const preservedMaterials=await sql('SELECT id,appliance_id,product_id,quantity::float8 quantity,unit_price::float8 unit_price FROM service_materials WHERE service_id=$1',[visitId]);
const preservedDevices=preservedAppliances.map(device=>({notes:device.notes,services:deletedTypeTasks.filter(task=>task.appliance_id===device.id).map(task=>({id:task.id,service_type_id:task.service_type_id,is_legacy:!task.service_type_id,unit_price:task.unit_price})),materials:preservedMaterials.filter(material=>material.appliance_id===device.id).map(material=>({id:material.id,product_id:material.product_id,quantity:material.quantity,unit_price:material.unit_price}))}));
const afterDeleteVersion=(await sql('SELECT version FROM services WHERE id=$1',[visitId]))[0].version;
await rpc('save_service_visit',[visitId,visit,preservedDevices,false,crypto.randomUUID(),afterDeleteVersion]);
equal((await sql('SELECT name_snapshot,unit_price::float8 FROM performed_services WHERE name_snapshot=$1',["Limpeza"]))[0],{name_snapshot:'Limpeza',unit_price:100});
const protectedServiceType=(await sql("INSERT INTO service_types(name,default_price) VALUES('Tipo protegido',10) RETURNING id"))[0].id;
await as(op);
await fails(()=>rpc('delete_service_type',[protectedServiceType]),/administradores/);
equal((await sql('SELECT count(*)::integer n FROM service_types WHERE id=$1',[protectedServiceType]))[0].n,1);
await as(admin);
await sql("UPDATE service_types SET is_active=false WHERE id=$1",[protectedServiceType]);
equal((await sql('SELECT is_active FROM service_types WHERE id=$1',[protectedServiceType]))[0].is_active,false);
equal((await sql('SELECT name_snapshot,unit_price::float8 FROM performed_services WHERE name_snapshot=$1',["Limpeza"]))[0],{name_snapshot:'Limpeza',unit_price:100});
await sql("UPDATE service_types SET is_active=true WHERE id=$1",[protectedServiceType]);
equal((await sql('SELECT is_active FROM service_types WHERE id=$1',[protectedServiceType]))[0].is_active,true);
await as(op);
await fails(()=>rpc('delete_product',[productY]),/administradores/);
equal((await sql('SELECT count(*)::integer n FROM products WHERE id=$1',[productY]))[0].n,1);
await as(admin);
equal(await rpc('get_product_balance',[productY]),2);
await db.exec('RESET ROLE');
await db.exec(`CREATE FUNCTION public.fail_product_delete_for_test() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'falha proposital no teste'; END $$`);
await db.exec(`CREATE TRIGGER fail_product_delete_for_test BEFORE DELETE ON public.products FOR EACH ROW WHEN (OLD.name='Capacitor') EXECUTE FUNCTION public.fail_product_delete_for_test()`);
await as(admin);
await fails(()=>rpc('delete_product',[productY]),/falha proposital no teste/);
equal((await sql('SELECT count(*)::integer n FROM products WHERE id=$1',[productY]))[0].n,1);
equal((await sql('SELECT count(*)::integer n FROM movements WHERE product_id=$1',[productY]))[0].n>0,true);
equal((await sql('SELECT count(*)::integer n FROM service_materials WHERE product_id=$1',[productY]))[0].n>0,true);
await db.exec('RESET ROLE');
await db.exec('DROP TRIGGER fail_product_delete_for_test ON public.products; DROP FUNCTION public.fail_product_delete_for_test()');
await as(admin);
await rpc('delete_product',[productY]);
equal((await sql('SELECT count(*)::integer n FROM products WHERE id=$1',[productY]))[0].n,0);
equal((await sql('SELECT count(*)::integer n FROM movements WHERE product_id=$1',[productY]))[0].n,0);
equal((await sql('SELECT count(*)::integer n FROM service_materials WHERE product_id=$1',[productY]))[0].n,0);
await db.exec('RESET ROLE');
equal((await sql('SELECT count(*)::integer n FROM product_code_aliases WHERE product_id=$1',[productY]))[0].n,0);
await db.exec('SET ROLE authenticated');
equal((await sql('SELECT count(*)::integer n FROM services WHERE id=$1',[visitId]))[0].n,1);
equal((await sql('SELECT count(*)::integer n FROM performed_services WHERE appliance_id IN (SELECT id FROM service_appliances WHERE service_id=$1)',[visitId]))[0].n,3);
equal((await sql('SELECT count(*)::integer n FROM service_materials WHERE service_id=$1 AND product_id=$2',[visitId,product]))[0].n,1);
const emptyProduct=await createProduct({name:'Sem histórico'});
const removedCode=(await sql('SELECT code FROM products WHERE id=$1',[emptyProduct]))[0].code;
await rpc('delete_product',[emptyProduct]);
equal((await sql('SELECT count(*)::integer n FROM products WHERE id=$1',[emptyProduct]))[0].n,0);
const afterDeleteProduct=await createProduct({name:'Criado após exclusão'});
const afterDeleteCode=(await sql('SELECT code FROM products WHERE id=$1',[afterDeleteProduct]))[0].code;
equal(afterDeleteCode===removedCode,false);
equal(Number(afterDeleteCode.slice(5))>Number(removedCode.slice(5)),true);
const archivedClient=(await sql("INSERT INTO clients(name) VALUES('Cliente Arquivado') RETURNING id"))[0].id;
const archivedVisit=await rpc('save_service_visit',[null,{...visit,client_id:archivedClient},[{notes:'Unidade de teste',services:[{id:null,service_type_id:protectedServiceType,unit_price:100}],materials:[]}],false,crypto.randomUUID(),null]);
const archivedAppliance=(await sql('SELECT id FROM service_appliances WHERE service_id=$1',[archivedVisit]))[0].id;
equal((await sql('SELECT count(*)::integer n FROM performed_services WHERE appliance_id=$1',[archivedAppliance]))[0].n,1);
await fails(()=>rpc('permanently_delete_archived_client',[archivedClient,'Cliente Arquivado']),/precisa ser arquivado/);
await db.exec('RESET ROLE');
await sql("INSERT INTO movements(product_id,type,quantity,unit_cost,responsible,notes,client_id,service_id,created_by) VALUES($1,'saida',-0.25,5,'Teste','Lançamento preservado',$2,$3,$4)",[product,archivedClient,archivedVisit,admin]);
await db.exec('SET ROLE authenticated');
const preservedMovement=(await sql('SELECT id FROM movements WHERE client_id=$1 AND service_id=$2',[archivedClient,archivedVisit]))[0].id;
await rpc('set_client_archived',[archivedClient,true]);
equal(Boolean((await sql('SELECT archived_at FROM clients WHERE id=$1',[archivedClient]))[0].archived_at),true);
await fails(()=>rpc('save_service_visit',[null,{...visit,client_id:archivedClient},[{notes:'Novo',services:[],materials:[]}],false,crypto.randomUUID(),null]),/Cliente arquivado/);
await as(op);
await fails(()=>rpc('permanently_delete_archived_client',[archivedClient,'Cliente Arquivado']),/administradores/);
await fails(()=>rpc('set_client_archived',[archivedClient,false]),/administradores/);
await as(admin);
await fails(()=>rpc('permanently_delete_archived_client',[archivedClient,'Cliente arquivado']),/não corresponde exatamente/);
await fails(()=>sql('DELETE FROM clients WHERE id=$1',[archivedClient]),/permission denied/);
await rpc('set_client_archived',[archivedClient,false]);
equal((await sql('SELECT archived_at FROM clients WHERE id=$1',[archivedClient]))[0].archived_at,null);
await fails(()=>rpc('permanently_delete_archived_client',[archivedClient,'Cliente Arquivado']),/precisa ser arquivado/);
await rpc('set_client_archived',[archivedClient,true]);
await sql('INSERT INTO test_client_delete_guard(client_id) VALUES($1)',[archivedClient]);
await fails(()=>rpc('permanently_delete_archived_client',[archivedClient,'Cliente Arquivado']),/test_client_delete_guard/);
equal((await sql('SELECT count(*)::integer n FROM services WHERE id=$1',[archivedVisit]))[0].n,1);
equal((await sql('SELECT count(*)::integer n FROM service_appliances WHERE service_id=$1',[archivedVisit]))[0].n,1);
equal((await sql('SELECT count(*)::integer n FROM performed_services WHERE appliance_id=$1',[archivedAppliance]))[0].n,1);
equal((await sql('SELECT count(*)::integer n FROM movements WHERE id=$1 AND client_id=$2 AND service_id=$3',[preservedMovement,archivedClient,archivedVisit]))[0].n,1);
await sql('DELETE FROM test_client_delete_guard WHERE client_id=$1',[archivedClient]);
equal((await sql('SELECT count(*)::integer n FROM services WHERE id=$1',[archivedVisit]))[0].n,1);
await rpc('permanently_delete_archived_client',[archivedClient,'Cliente Arquivado']);
equal((await sql('SELECT count(*)::integer n FROM clients WHERE id=$1',[archivedClient]))[0].n,0);
equal((await sql('SELECT count(*)::integer n FROM services WHERE id=$1',[archivedVisit]))[0].n,0);
equal((await sql('SELECT count(*)::integer n FROM service_appliances WHERE service_id=$1',[archivedVisit]))[0].n,0);
equal((await sql('SELECT count(*)::integer n FROM performed_services WHERE appliance_id=$1',[archivedAppliance]))[0].n,0);
equal((await sql('SELECT client_id,service_id,quantity::float8 FROM movements WHERE id=$1',[preservedMovement]))[0],{client_id:null,service_id:null,quantity:-0.25});
const clientWithPayment=(await sql("INSERT INTO clients(name) VALUES('Cliente com pagamento') RETURNING id"))[0].id;
const paidArchivedVisit=await rpc('save_service_visit',[null,{...visit,client_id:clientWithPayment},[{notes:'Unidade paga',services:[{id:null,service_type_id:protectedServiceType,unit_price:100}],materials:[]}],false,crypto.randomUUID(),null]);
const paidArchivedNumber=(await sql('SELECT number FROM services WHERE id=$1',[paidArchivedVisit]))[0].number;
await db.exec('RESET ROLE');
const paidArchivedEvent=(await sql("INSERT INTO service_payment_events(service_id,amount,payment_date,payment_method,paid_by,posted_to_cash) VALUES($1,100,$2,'pix',$3,true) RETURNING id",[paidArchivedVisit,registerDate,admin]))[0].id;
const paidArchivedMovement=(await sql("INSERT INTO cash_movements(cash_register_id,type,description,amount,payment_method,source,service_id,payment_event_id,created_by,created_by_name) VALUES($1,'entrada',$2,100,'pix','service_payment',$3,$4,$5,'Cj') RETURNING id",[cashRegister,`Pagamento do Serviço #${paidArchivedNumber}`,paidArchivedVisit,paidArchivedEvent,admin]))[0].id;
await db.exec('SET ROLE authenticated');
await rpc('set_client_archived',[clientWithPayment,true]);
await rpc('permanently_delete_archived_client',[clientWithPayment,'Cliente com pagamento']);
await db.exec('RESET ROLE');
equal((await sql('SELECT service_id,amount::float8,payment_method,posted_to_cash FROM service_payment_events WHERE id=$1',[paidArchivedEvent]))[0],{service_id:null,amount:100,payment_method:'pix',posted_to_cash:true});
equal((await sql('SELECT service_id,description,amount::float8,payment_event_id FROM cash_movements WHERE id=$1',[paidArchivedMovement]))[0],{service_id:null,description:`Pagamento do Serviço #${paidArchivedNumber}`,amount:100,payment_event_id:paidArchivedEvent});
await db.exec('RESET ROLE');
equal((await sql('SELECT count(*)::integer n FROM operation_requests WHERE actor=$1',[op]))[0].n>0,true);
equal((await sql("SELECT count(*)::integer n FROM service_history WHERE service_id=$1 AND user_name='Operador'",[service]))[0].n>0,true);
await fails(()=>sql('DELETE FROM auth.users WHERE id=$1',[admin]),/último administrador/);
equal((await sql('SELECT count(*)::integer n FROM auth.users WHERE id=$1',[admin]))[0].n,1);
await sql('DELETE FROM auth.users WHERE id=$1',[op]);
equal((await sql('SELECT count(*)::integer n FROM profiles WHERE id=$1',[op]))[0].n,0);
equal((await sql('SELECT created_by FROM services WHERE id=$1',[service]))[0].created_by,null);
equal((await sql('SELECT count(*)::integer n FROM movements WHERE created_by=$1',[op]))[0].n,0);
equal((await sql("SELECT count(*)::integer n FROM service_history WHERE service_id=$1 AND user_name='Operador'",[service]))[0].n>0,true);
equal((await sql('SELECT count(*)::integer n FROM operation_requests WHERE actor=$1',[op]))[0].n,0);
await as(admin);
registerSnapshot=await rpc('cash_register_snapshot',[cashRegister]);
equal(registerSnapshot.opening_user_name,'Operador');
equal(registerSnapshot.movements.find(m=>m.description==='Combustível').created_by_name,'Operador');
const preventiveType=(await sql("INSERT INTO service_types(name,default_price,maintenance_enabled,maintenance_interval_months,maintenance_alert_days) VALUES('Preventiva teste',100,true,3,14) RETURNING id"))[0].id;
const applianceForMaintenance=(await sql("INSERT INTO client_appliances(client_id,name,location) VALUES($1,'Ar Sala','Sala'),($1,'Ar Quarto','Quarto') RETURNING id",[client])).map(row=>row.id);
const maintenanceService=await rpc('save_service_visit',[null,{...visit,service_date:'2026-09-30'},[{client_appliance_id:applianceForMaintenance[0],notes:'',services:[{id:null,service_type_id:preventiveType,unit_price:100}],materials:[]}],true,crypto.randomUUID(),null]);
const draftMaintenanceService=await rpc('save_service_visit',[null,{...visit,service_date:'2026-10-01'},[{client_appliance_id:applianceForMaintenance[1],notes:'',services:[{id:null,service_type_id:preventiveType,unit_price:100}],materials:[]}],false,crypto.randomUUID(),null]);
equal((await sql('SELECT payment_status,status FROM services WHERE id=$1',[maintenanceService]))[0],{payment_status:'pendente',status:'confirmado'});
equal((await sql('SELECT count(*)::integer n FROM maintenance_overview($1::date)', ['2026-12-16']))[0].n,1);
equal((await sql('SELECT client_appliance_id,next_maintenance_date::text,days_until,alert_days FROM maintenance_overview($1::date)', ['2026-12-16']))[0],{client_appliance_id:applianceForMaintenance[0],next_maintenance_date:'2026-12-30',days_until:14,alert_days:14});
equal((await sql('SELECT days_until FROM maintenance_overview($1::date)', ['2026-12-30']))[0].days_until,0);
equal((await sql('SELECT days_until FROM maintenance_overview($1::date)', ['2027-01-01']))[0].days_until,-2);
await sql('UPDATE service_types SET maintenance_interval_months=4,maintenance_alert_days=20 WHERE id=$1',[preventiveType]);
equal((await sql('SELECT maintenance_interval_months_snapshot,maintenance_alert_days_snapshot FROM performed_services WHERE appliance_id IN (SELECT id FROM service_appliances WHERE service_id=$1)',[maintenanceService]))[0],{maintenance_interval_months_snapshot:3,maintenance_alert_days_snapshot:14});
await rpc('delete_service_type',[preventiveType]);
equal((await sql('SELECT service_type_id,maintenance_enabled_snapshot,maintenance_interval_months_snapshot FROM performed_services WHERE appliance_id IN (SELECT id FROM service_appliances WHERE service_id=$1)',[maintenanceService]))[0],{service_type_id:null,maintenance_enabled_snapshot:true,maintenance_interval_months_snapshot:3});
equal((await sql('SELECT next_maintenance_date::text FROM maintenance_overview($1::date)', ['2026-12-16']))[0].next_maintenance_date,'2026-12-30');
await rpc('cancel_service',[maintenanceService,[]]);
equal((await sql('SELECT count(*)::integer n FROM maintenance_overview($1::date)', ['2026-12-16']))[0].n,0);
equal((await sql('SELECT count(*)::integer n FROM services WHERE id=$1 AND status=\'rascunho\'',[draftMaintenanceService]))[0].n,1);
await as(op);
await fails(()=>sql("INSERT INTO client_appliances(client_id,name) VALUES($1,'Sem permissão')",[client]),/row-level security policy/);
await as(pending);equal(await sql('SELECT id FROM products'),[]);await fails(()=>balance(),/não autorizado/);
await as(null);await fails(()=>balance(),/permission denied/);

await as(admin);
const appointmentType=(await sql("INSERT INTO service_types(name,default_price) VALUES('Tipo agenda',100) RETURNING id"))[0].id;
const appointmentData={client_id:client,scheduled_date:'2026-10-01',scheduled_time:'08:00',technician:'Carlos',service_type_id:appointmentType,status:'agendado',notes:'Agenda'};
const appointmentId=await rpc('save_appointment',[null,appointmentData,applianceForMaintenance,null]);
equal((await sql('SELECT created_by,technician,status FROM appointments WHERE id=$1',[appointmentId]))[0],{created_by:admin,technician:'Carlos',status:'agendado'});
equal((await sql('SELECT count(*)::integer n FROM appointment_appliances WHERE appointment_id=$1',[appointmentId]))[0].n,2);
await fails(()=>rpc('save_appointment',[null,appointmentData,[applianceForMaintenance[0],applianceForMaintenance[0]],null]),/duplicado/);
const foreignClient=(await sql("INSERT INTO clients(name) VALUES('Outro cliente agenda') RETURNING id"))[0].id;
await fails(()=>rpc('save_appointment',[null,{...appointmentData,client_id:foreignClient},[applianceForMaintenance[0]],null]),/não pertence/);
const agendaOperator='44444444-4444-4444-8444-444444444444';
await db.exec('RESET ROLE');
await sql("INSERT INTO auth.users(id) VALUES($1)",[agendaOperator]);
await as(admin); await rpc('set_user_access',[agendaOperator,'operador',true]);
await as(agendaOperator);
await fails(()=>sql("UPDATE appointments SET status='concluido' WHERE id=$1",[appointmentId]),/permission denied/);
await rpc('save_appointment',[appointmentId,{...appointmentData,scheduled_time:'09:00'},applianceForMaintenance,1]);
equal((await sql('SELECT scheduled_time::text,version FROM appointments WHERE id=$1',[appointmentId]))[0],{scheduled_time:'09:00:00',version:2});
await fails(()=>rpc('save_appointment',[appointmentId,appointmentData,applianceForMaintenance,1]),/outro usuário/);
await fails(()=>rpc('save_appointment',[appointmentId,{...appointmentData,status:'concluido'},applianceForMaintenance,2]),/fluxo de serviços/);
const cancelAppointment=await rpc('save_appointment',[null,appointmentData,[],null]);
await rpc('save_appointment',[cancelAppointment,{...appointmentData,status:'cancelado'},[],1]);
equal((await sql('SELECT status FROM appointments WHERE id=$1',[cancelAppointment]))[0].status,'cancelado');
const appointmentVisit=[{client_appliance_id:applianceForMaintenance[0],notes:'',services:[{id:null,service_type_id:appointmentType,unit_price:100}],materials:[]}];
const appointmentRequest=crypto.randomUUID();
const appointmentService=await rpc('save_appointment_service',[appointmentId,null,{...visit,client_id:client},appointmentVisit,false,appointmentRequest,null]);
equal((await sql('SELECT status,completed_service_id FROM appointments WHERE id=$1',[appointmentId]))[0],{status:'agendado',completed_service_id:appointmentService});
equal(await rpc('save_appointment_service',[appointmentId,null,{...visit,client_id:client},appointmentVisit,false,appointmentRequest,null]),appointmentService);
await rpc('confirm_service',[appointmentService]);
equal((await sql('SELECT status FROM appointments WHERE id=$1',[appointmentId]))[0].status,'concluido');
await rpc('cancel_service',[appointmentService,[]]);
equal((await sql('SELECT status FROM appointments WHERE id=$1',[appointmentId]))[0].status,'concluido');
equal((await sql("SELECT count(*)::integer n FROM service_history WHERE appointment_id=$1 AND action='conclusao'",[appointmentId]))[0].n,1);

const hoursAppointment=await rpc('save_appointment',[null,{...appointmentData,duration_minutes:180},[applianceForMaintenance[0]],null]);
equal((await sql('SELECT duration_minutes FROM appointments WHERE id=$1',[hoursAppointment]))[0].duration_minutes,180);
await rpc('save_appointment',[hoursAppointment,{...appointmentData,duration_minutes:210},[applianceForMaintenance[0]],1]);
equal((await sql('SELECT duration_minutes FROM appointments WHERE id=$1',[hoursAppointment]))[0].duration_minutes,210);
for (const duration_minutes of [0,-30,60,179]) await fails(()=>rpc('save_appointment',[null,{...appointmentData,duration_minutes},[],null]),/pelo menos 3 horas/);
await fails(()=>rpc('save_appointment',[hoursAppointment,{...appointmentData,duration_minutes:179},[],2]),/pelo menos 3 horas/);
equal((await sql('SELECT duration_minutes,version FROM appointments WHERE id=$1',[hoursAppointment]))[0],{duration_minutes:210,version:2});
// Legacy durations are not rewritten, and unrelated status changes remain possible.
await db.exec('RESET ROLE; ALTER TABLE appointments DISABLE TRIGGER appointments_validate_duration;');
const legacyAppointment=(await sql("INSERT INTO appointments(client_id,scheduled_date,scheduled_time,duration_minutes,created_by) VALUES($1,'2026-10-01','07:30',60,$2) RETURNING id",[client,admin]))[0].id;
await db.exec('ALTER TABLE appointments ENABLE TRIGGER appointments_validate_duration;');
await as(agendaOperator);
await rpc('save_appointment',[legacyAppointment,{...appointmentData,status:'cancelado',duration_minutes:60},[],1]);
equal((await sql('SELECT duration_minutes,status FROM appointments WHERE id=$1',[legacyAppointment]))[0],{duration_minutes:60,status:'cancelado'});
const manualService=await rpc('save_service_visit',[null,{...visit,client_id:client,technician:'Queticia'},appointmentVisit,false,crypto.randomUUID(),null]);
equal((await sql('SELECT technician,created_by FROM services WHERE id=$1',[manualService]))[0],{technician:'Queticia',created_by:agendaOperator});
const manualVersion=(await sql('SELECT version FROM services WHERE id=$1',[manualService]))[0].version;
await rpc('save_service_visit',[manualService,{...visit,client_id:client,technician:'Pedro'},appointmentVisit,false,crypto.randomUUID(),manualVersion]);
equal((await sql('SELECT technician,created_by FROM services WHERE id=$1',[manualService]))[0],{technician:'Pedro',created_by:agendaOperator});
await rpc('confirm_service',[manualService]);
equal((await sql('SELECT technician FROM services WHERE id=$1',[manualService]))[0].technician,'Pedro');
await as(pending);equal(await sql('SELECT id FROM appointments'),[]);await fails(()=>rpc('save_appointment',[null,appointmentData,[],null]),/não autorizado/);
await as(null);await fails(()=>rpc('save_appointment',[null,appointmentData,[],null]),/permission denied/);


await as(admin);
const recentMovements=await sql(`SELECT m.id,m.created_at,m.type,m.quantity,p.name AS product_name FROM movements m LEFT JOIN products p ON p.id=m.product_id ORDER BY m.created_at DESC NULLS LAST,m.id DESC LIMIT 10`);
equal(recentMovements.length,10);
equal(new Set(recentMovements.map(m=>m.id)).size,recentMovements.length);
equal(recentMovements.every((m,i)=>i===0 || new Date(recentMovements[i-1].created_at)>=new Date(m.created_at)),true);
const correctionPairs=await sql(`SELECT original.id,original.quantity::float8 quantity,reversal.id AS reversal_id,reversal.quantity::float8 reversal_quantity FROM movements original JOIN movements reversal ON reversal.reversal_of=original.id WHERE original.type='saida' AND reversal.type='estorno'`);
equal(correctionPairs.length>0,true);
equal(correctionPairs.every(m=>m.id!==m.reversal_id && m.quantity===-m.reversal_quantity),true);

{
await as(admin);
const auditProduct=await createProduct({name:'Material auditoria',unit_cost:2,unit_price:5});
await rpc('register_movement',[auditProduct,'entrada',10,2,'','Auditoria',crypto.randomUUID()]);
const auditType=(await sql("INSERT INTO service_types(name,default_price) VALUES('Tipo auditoria',50) RETURNING id"))[0].id;
const auditClient=(await sql("INSERT INTO clients(name) VALUES('Cliente auditoria') RETURNING id"))[0].id;
const auditDevice=(await sql("INSERT INTO client_appliances(client_id,name) VALUES($1,'Aparelho auditoria') RETURNING id",[auditClient]))[0].id;
const auditData={client_id:auditClient,service_date:'2026-10-02',description:'Auditoria estoque',technician:'Carlos',discount:0,notes:''};
const auditDevices=[{client_appliance_id:auditDevice,notes:'',services:[{id:null,service_type_id:auditType,unit_price:50}],materials:[{id:null,product_id:auditProduct,quantity:1,unit_price:5}]}];
const auditRequest=crypto.randomUUID();
const auditService=await rpc('save_service_visit',[null,auditData,auditDevices,true,auditRequest,null]);
equal(await rpc('get_product_balance',[auditProduct]),9);
equal(await rpc('save_service_visit',[null,auditData,auditDevices,true,auditRequest,null]),auditService);
equal(await rpc('get_product_balance',[auditProduct]),9);
async function auditServicePayload() {
 const task=(await sql('SELECT ps.* FROM performed_services ps JOIN service_appliances sa ON sa.id=ps.appliance_id WHERE sa.service_id=$1',[auditService]))[0];
 const material=(await sql('SELECT * FROM service_materials WHERE service_id=$1',[auditService]))[0];
 return [{client_appliance_id:auditDevice,notes:'',services:[{id:task.id,service_type_id:task.service_type_id,unit_price:50}],materials:material?[{id:material.id,product_id:auditProduct,quantity:Number(material.quantity),unit_price:5}]:[]}];
}
async function auditEdit(devices) {
 const version=(await sql('SELECT version FROM services WHERE id=$1',[auditService]))[0].version;
 return rpc('save_service_visit',[auditService,auditData,devices,true,crypto.randomUUID(),version]);
}
await sql("UPDATE service_types SET name='Nome mestre atualizado' WHERE id=$1",[auditType]);
await auditEdit(await auditServicePayload());
equal(await rpc('get_product_balance',[auditProduct]),9);
equal((await sql('SELECT name_snapshot FROM performed_services ps JOIN service_appliances sa ON sa.id=ps.appliance_id WHERE sa.service_id=$1',[auditService]))[0].name_snapshot,'Tipo auditoria');
let editedDevices=await auditServicePayload();editedDevices[0].materials=[];
await auditEdit(editedDevices);equal(await rpc('get_product_balance',[auditProduct]),10);
editedDevices=await auditServicePayload();editedDevices[0].materials=[{id:null,product_id:auditProduct,quantity:1,unit_price:5}];
await auditEdit(editedDevices);equal(await rpc('get_product_balance',[auditProduct]),9);
const returnMaterial=(await sql('SELECT id FROM service_materials WHERE service_id=$1',[auditService]))[0].id;
await rpc('cancel_service',[auditService,[returnMaterial]]);equal(await rpc('get_product_balance',[auditProduct]),10);
const draftAudit=await rpc('save_service_visit',[null,auditData,auditDevices,false,crypto.randomUUID(),null]);
await rpc('delete_draft_service',[draftAudit]);equal(await rpc('get_product_balance',[auditProduct]),10);
const requestAppointment=crypto.randomUUID();
const appointmentPayload={client_id:auditClient,scheduled_date:'2026-10-02',scheduled_time:'07:30',duration_minutes:180,technician:'Carlos',status:'agendado',service_type_id:auditType};
const retryAppointment=await rpc('save_appointment',[null,appointmentPayload,[auditDevice],null,requestAppointment]);
equal(await rpc('save_appointment',[null,appointmentPayload,[auditDevice],null,requestAppointment]),retryAppointment);
await fails(()=>rpc('save_appointment',[null,{...appointmentPayload,technician:'Outro'},[auditDevice],null,requestAppointment]),/dados diferentes/);
const linkedRequest=crypto.randomUUID();
const linkedAudit=await rpc('save_appointment_service',[retryAppointment,null,auditData,auditDevices,false,linkedRequest,null]);
equal(await rpc('save_appointment_service',[retryAppointment,null,auditData,auditDevices,false,linkedRequest,null]),linkedAudit);
await fails(()=>rpc('save_appointment_service',[retryAppointment,null,{...auditData,technician:'João'},auditDevices,false,crypto.randomUUID(),null]),/já possui atendimento/);
const archivedAppointment=await rpc('save_appointment',[null,appointmentPayload,[auditDevice],null,crypto.randomUUID()]);
await rpc('set_client_archived',[auditClient,true]);await sql('UPDATE client_appliances SET is_active=false WHERE id=$1',[auditDevice]);
await rpc('save_appointment',[archivedAppointment,{...appointmentPayload,status:'cancelado'},[auditDevice],1,crypto.randomUUID()]);
equal((await sql('SELECT status FROM appointments WHERE id=$1',[archivedAppointment]))[0].status,'cancelado');
// User deletion is local fixture deletion, never a production action.
await db.exec('RESET ROLE');await sql('DELETE FROM auth.users WHERE id=$1',[agendaOperator]);await as(admin);
equal((await sql('SELECT created_by,created_by_name FROM appointments WHERE id=$1',[appointmentId]))[0].created_by,admin);
equal((await sql('SELECT created_by,created_by_name FROM appointments WHERE id=$1',[cancelAppointment]))[0],{created_by:null,created_by_name:'Usuário'});
// Reopen only an isolated local fixture to exercise retry after closure.
await db.exec('RESET ROLE');await sql("UPDATE cash_registers SET status='aberto',closing_balance=NULL,expected_cash=NULL,counted_cash=NULL,difference=NULL,closing_reason=NULL,closed_by=NULL,closed_by_name='',closed_at=NULL WHERE id=$1",[cashRegister]);await as(admin);
const cashRequest=crypto.randomUUID();
const cashRetry=await rpc('record_cash_movement',[cashRegister,'entrada','Auditoria idempotência',5,'dinheiro',null,cashRequest]);
equal(await rpc('record_cash_movement',[cashRegister,'entrada','Auditoria idempotência',5,'dinheiro',null,cashRequest]),cashRetry);
equal((await rpc('cash_register_snapshot',[cashRegister])).movements.filter(m=>m.id===cashRetry).length,1);
await fails(()=>rpc('record_cash_movement',[cashRegister,'entrada','Auditoria idempotência',6,'dinheiro',null,cashRequest]),/dados diferentes/);
const finalCash=await rpc('cash_register_snapshot',[cashRegister]);await rpc('close_cash_register',[cashRegister,finalCash.expected_cash_live,null]);
equal(await rpc('record_cash_movement',[cashRegister,'entrada','Auditoria idempotência',5,'dinheiro',null,cashRequest]),cashRetry);
}
await db.close();console.log(`PASS: migrations and ${checks} database assertions (roles, atomic rollback, idempotency, corrections, payments, returns, import, preventive maintenance).`);
